# This file was generated by DAGfactory in GitSync at: 2025-11-07 23:35:57 IST
"""
"""

from airflow.decorators import dag, task
from airflow import utils
from airflow.models.baseoperator import chain
from datetime import datetime, timedelta
from airflow.utils.db import provide_session
from airflow.models import XCom
import yaml

# DAG
default_args = {
    'owner':'airflow',
    'start_date': utils.dates.days_ago(2),
    'provide_context': True,
    'depends_on_past':False,
    'email': ['DAGfactory@gmail.com'],
    'email_on_failure':False,
    'email_on_retry':False,
    'retries':1,
    'retry_delay':timedelta(minutes=1)
}

@dag(
    dag_id="COMEX_ARG",
    default_args=default_args,
    schedule_interval=None,
    catchup=False,
    tags=['COMEX'],
    max_active_runs=1 
)

# Define tasks
def init():
    import sys
    import os
    airflow_include_path = os.getenv('AIRFLOW_INCLUDE_PATH', '/opt/airflow/include')
    sys.path.append(airflow_include_path)
    
    from COMEX_ARG import COMEX_ARG

    @task()
    def coleta():
        bot = COMEX_ARG()
        bot.collect()
    
        
    @task()
    def tratamento():
        bot = COMEX_ARG()
        bot.treat()
        
    @task()
    def calculo():
        bot = COMEX_ARG()
        bot.calculate()
        
    # Tasks chain
    step_coleta = coleta()
    step_tratamento = tratamento()
    step_calculo = calculo()
    
    step_coleta >> step_tratamento >> step_calculo

dag_def = init()

